### ISSUE TITLE
appcompat-v7:23.3.0  

### ISSUE THREAD

**Issue by DarkVio** [medyo/android-about-page#11] opened 2016-04-26 08:05 UTC
If i using appcompat-v7:23.3.0  have android.content.res.Resources$NotFoundException:
ImageView change AppCompatImageView work fine...

**Comment by skmlcd** [comment] 2016-04-26 11:23
Well, I'm using appcompat-v7:23.3.0 and do not have that problem. Any more details?

**Comment by DarkVio** [comment] 2016-04-26 13:54
compileSdkVersion 23
buildToolsVersion '24.0.0 rc2'
vectorDrawables.useSupportLibrary = true
gradleVersion = '2.10'
classpath 'com.android.tools.build:gradle:2.1.0-beta1'

**Comment by Salat-Cx65** [comment] 2016-04-26 14:17
The same issue with latest AppCompat
Suggested solution for AppCompat http://android-developers.blogspot.com.au/2016/02/android-support-library-232.html doesn't have affect

**Comment by medyo** [comment] 2016-04-26 21:52
@Salat-Cx65 How could we reproduce your issue ? could you share with us a code example

**Comment by NumezmaT** [comment] 2016-04-27 07:40
compile 'com.android.support:appcompat-v7:23.3.0' 
causes an error because vector images

**Comment by T4RDIS** [comment] 2016-04-27 07:48
I will make awesome apps. Like always ;P :D.


Yeah, that's my ego! 😙

2016-04-27 9:40 GMT+02:00 NumezmaT <notifications@github.com>:

**Comment by medyo** [comment] 2016-04-27 22:50
Fixed by @NumezmaT #18, it should be available in the coming version

**Closed by medyo** 2016-04-27 22:50 UTC
